### ISSUE TITLE
Printing Mural Posters for Office

### ISSUE THREAD

**Issue by shawnroos** [we-are-next/office#10]
@shawnroos @FrancoRaffa Need quotes approved.

https://docs.google.com/spreadsheets/d/1IJiH-6c3r0V6zTTvrcYl6E9ii81SpbWi5c7l7APafvE/edit#gid=0

**Comment by FrancoRaffa** [comment]
I'm happy with those quotes - welcome to choose which is best and go ahead - I just need the invoice and will make payment.

**Comment by ulandamackay** [comment]
@FrancoRaffa Awesome :) Shared files with printers and requested invoice.
