### ISSUE TITLE
Table tennis table 

### ISSUE THREAD

**Issue by FrancoRaffa** [we-are-next/office#6]

**Comment by mieliep** [comment]
This is a priority

**Comment by wayneashleyberry** [comment]
I'd rather we get an Xbox or something... then we can play virtual table tennis, or, you know, Gears of War.

**Comment by michaelthorne** [comment]
Also: https://www.youtube.com/watch?v=7cIIW0p7bJg

**Comment by FrancoRaffa** [comment]
Love that sound. So it's a go :-) Oh crap, wasn't I suppose to get aircon
installed 1st?


FRANCO RAFFA | MD
+27(0)21 447 0058 | +27(0)82 333 0030 | www.wearenext.co.za
