### ISSUE TITLE
Mellerware

### ISSUE THREAD

**Issue by Warra** [we-are-next/office#7]
Has anyone ever used that Mellerware thing?

**Comment by wayneashleyberry** [comment]
Huh?

**Comment by FrancoRaffa** [comment]
Yes, You can use it. It's a single stove top. Not an issue :-)

**Comment by michaelthorne** [comment]
![image](https://cloud.githubusercontent.com/assets/2629322/14138475/af371f72-f66d-11e5-83c2-5164aedd4d0a.png)
